// Auto-generated tips from X100VI manual
export const TIPS: string[] = [
  "Use Custom Settings (C1–C7) to save your favorite film simulation recipes — go to IMAGE QUALITY SETTING > EDIT/SAVE CUSTOM SETTING and store everything from grain to tone curve so you can switch looks instantly.",
  "Assign FILM SIMULATION to the control ring (Fn2 button) so you can cycle through Provia, Velvia, Classic Chrome, and more without diving into menus while shooting.",
  "Enable PRE-AF under G AF/MF SETTING so the camera continuously focuses even before you half-press the shutter — great for street and documentary shooting where speed matters.",
  "Switch to the OVF when shooting street to see outside the frame borders, helping you anticipate subjects entering the scene before they're in the shot.",
  "Turn on GRAIN EFFECT (set to STRONG, LARGE) with Acros film simulation for a punchy, classic black-and-white film look straight out of camera.",
  "Use AF-C CUSTOM SETTINGS to fine-tune tracking sensitivity and speed — for fast-moving subjects like kids or skateboarders, bump up the tracking sensitivity setting.",
  "Assign the built-in ND filter to a Function button via BUTTON/DIAL SETTING > FUNCTION (Fn) SETTING so you can toggle it on/off in bright light without going into menus.",
  "Use ZONE AF mode for moving subjects in a defined area — it's faster and less fussy than tracking the entire frame, perfect for events or sports.",
  "Enable SUBJECT DETECTION SETTING for animals or vehicles to let the camera automatically prioritize eye/body detection on your intended subject.",
  "Set RELEASE/FOCUS PRIORITY to RELEASE in AF-C mode if you're shooting fast action and can't afford missed frames — the camera will fire even if focus isn't perfectly locked.",
  "Use INTERLOCK SPOT AE & FOCUS AREA so your metering spot follows your AF point — essential for tricky backlit portraits where you want both focus and exposure on the subject.",
  "Try COLOR CHROME EFFECT set to STRONG with Velvia for incredibly saturated, deep colors in landscape and flower photography without blowing out hues.",
  "Customize your Q (Quick Menu) via BUTTON/DIAL SETTING > EDIT/SAVE QUICK MENU — put your most-used settings like WB, film sim, and ISO right there for one-button access.",
  "Use the SPORTS FINDER MODE under SHOOTING SETTING to see a cropped frame inside the OVF that shows exactly what will be captured, helping you track fast subjects.",
  "Enable FACE/EYE DETECTION SETTING and set it to EYE for portrait work — the camera will lock onto the nearest eye automatically, even when subjects are moving.",
  "Set ISO AUTO SETTING to cap your max ISO at 6400 for cleaner files, or push it to 12800 when shooting in very dark environments like concerts or restaurants.",
  "Use the TONE CURVE control in Image Quality settings to separately adjust highlight and shadow contrast — pull highlights down slightly for a more filmic, less clipped look.",
  "Assign DIGITAL TELE-CONV. to a Function button so you can quickly jump to the 35mm or 50mm equivalent crop when you need more reach without losing your wide setting.",
  "Turn on PREVIEW EXP/WB IN MANUAL MODE under SCREEN SETTING so the EVF shows you a live exposure preview — what you see is what you get, no surprises.",
  "Use MY MENU SETTING to pin your five most-accessed settings (like film sim, grain, WB, DR, and ISO auto) so you reach them with a single MENU button press.",
  "Set DYNAMIC RANGE to DR400 in high-contrast scenes like bright outdoor midday shots — it protects highlights significantly at the cost of needing ISO 800 or higher.",
  "Try D RANGE PRIORITY set to AUTO for everyday shooting — it intelligently balances shadow and highlight recovery without you having to manually adjust DR and tone curves.",
  "Shoot RAW + JPEG simultaneously by setting RAW RECORDING to ON — this lets you post-process the RAW later while still having a ready-to-share JPEG in your chosen film sim.",
  "Use MF ASSIST with DIGITAL SPLIT IMAGE for precise manual focus — the display splits the image and you align edges for tack-sharp focus, especially useful for macro work.",
  "Enable FOCUS CHECK by assigning it to a Function button — press it to instantly zoom into your focus point after a shot to verify sharpness before moving on.",
  "Use WRAP FOCUS POINT (G AF/MF SETTING > WRAP FOCUS POINT) so your focus point wraps from one edge of the frame to the other, saving time when repositioning quickly.",
  "Set FLICKER REDUCTION to ON when shooting under artificial lighting like fluorescent or LED panels to reduce banding and exposure inconsistency across burst shots.",
  "Use INTERVAL TIMER SHOOTING with EXPOSURE SMOOTHING ON for timelapse work — it automatically adjusts exposure gradually between frames for smooth day-to-night transitions.",
  "Assign AE/AF-LOCK to the AEL button in HOLD mode so you can lock exposure separately from focus — perfect for recomposing shots after metering off a specific tone.",
  "Try Classic Neg film simulation for street and documentary work — it has a slightly faded, shifted color palette that feels nostalgic and cinematic straight from the camera.",
  "Use COLOR CHROME FX BLUE set to STRONG with Velvia or Classic Chrome to deepen and saturate blue skies and water tones without over-saturating other colors.",
  "Set SHUTTER TYPE to MECHANICAL for important shots around LED lighting or screens — electronic shutter can cause banding with certain artificial light sources.",
  "Use the ELECTRONIC SHUTTER for completely silent shooting in quiet environments like weddings, theater, or street work — set it in SHOOTING SETTING > SHUTTER TYPE.",
  "Assign WHITE BALANCE to the control ring for quick shifts between presets — great when moving between indoor tungsten light and outdoor daylight rapidly.",
  "Set AWB-LOCK MODE to ON-SHOT so auto white balance locks when you half-press the shutter, preventing color shifts between shots in the same scene.",
  "Use PRE-SHOT mode (DRIVE menu > PRE-SHOT) to capture up to 1 second of frames before you fully press the shutter — perfect for unpredictable moments like animal behavior.",
  "Enable SMOOTH SKIN EFFECT for portrait sessions when shooting JPEG — it subtly softens skin texture without an obvious retouched look, saving editing time.",
  "Try Eterna Cinema film simulation for video — its low saturation, gentle contrast, and wide dynamic range give you a flat cinematic starting point ideal for color grading.",
  "Use the MONOCHROMATIC COLOR option with Acros to add a colored tint (warm, cool, or green) to your black-and-white images for creative effect without Lightroom.",
  "Set PERFORMANCE to BOOST mode under POWER MANAGEMENT when shooting fast action — it maximizes AF speed, burst rate, and EVF refresh at the cost of battery life.",
  "Assign VIEW MODE SETTING to a Function button so you can instantly flip between the EVF, OVF, and LCD without going into the setup menu.",
  "Use the ELECTRONIC LEVEL SETTING (SCREEN SETTING) to activate a virtual horizon in the EVF — it's invaluable for architecture and landscape shots where straight horizons matter.",
  "Set COMMAND DIAL DIRECTION to reverse if the default feels counter-intuitive for exposure adjustments — match it to how you instinctively think about changing values.",
  "Use TOUCH SCREEN MODE > FOCUS AREA SELECTION to tap the LCD to set your AF point while keeping your eye to the EVF — fast and intuitive for repositioning focus.",
  "Enable AF+MF so after the camera autofocuses, you can fine-tune manually with the focus ring — perfect for portraits or macro where you want AF speed plus manual precision.",
  "Set SHOOT WITHOUT CARD to OFF under BUTTON/DIAL SETTING to prevent accidentally shooting without a memory card inserted and losing your images.",
  "Use FOCUS BKT SETTING to shoot a focus bracket sequence automatically — the camera shifts focus slightly between frames so you can merge them for extended depth of field in macro.",
  "Try the Nostalgic Neg film simulation for portrait and lifestyle photography — it has a warm, faded analog aesthetic similar to expired film that works beautifully in natural light.",
  "Use CLARITY (in IMAGE QUALITY SETTING) set to +2 or +3 to add midtone contrast and punch to landscapes and urban scenes without sharpening edges artificially.",
  "Set HIGH ISO NR to -2 when shooting RAW — noise reduction in camera doesn't apply to RAW files anyway, and for JPEG it keeps more texture and detail at higher ISOs.",
  "Use the RATING function in the Playback Menu to mark your best shots with 1–5 stars in-camera — great for quick culling before you even get to your computer.",
  "Enable AUTO UPDATE CUSTOM SETTING so any changes you make while a Custom Setting is active are automatically saved back to that slot — no manual re-saving required.",
  "Use FILM SIMULATION BKT to shoot the same frame with three different film simulations simultaneously — perfect for deciding which look you prefer without reshooting.",
  "Set your AE BKT to ±1/3 or ±2/3 EV increments for subtle bracketing in tricky light, or go to ±1 EV for HDR merging in high-contrast scenes.",
  "Assign DEPTH-OF-FIELD SCALE to a function button to quickly check depth of field in the display when shooting in Manual Focus mode.",
  "Use STORE AF MODE BY ORIENTATION to set different AF modes for horizontal and vertical shooting — for example, single point for landscape and zone for portrait orientation.",
  "Try Bleach Bypass simulation (if available in your firmware) for a gritty, desaturated high-contrast look ideal for moody urban and dark portrait work.",
  "Use AF RANGE LIMITER to restrict the focus distance range — for example, when shooting portraits at close range, limit AF to 1–3m so it never hunts to infinity.",
  "Enable CORRECTED AF FRAME in the OVF to display a parallax-corrected focus frame that shows where the lens is actually focused, not just the viewfinder parallax estimate.",
  "Set SHUTTER AF to OFF if you want to separate focus from the shutter button — use back-button focus via the AEL button for more precise focus/recompose control.",
  "Use LARGE INDICATORS MODE in SCREEN SETTING for a simplified, clean display with big shutter speed, aperture, and ISO numbers — easier to read when shooting fast.",
  "Assign the HISTOGRAM to your DISP custom display so you always have a live exposure histogram visible in the EVF — prevents blown highlights before you shoot.",
  "Use LONG EXPOSURE NR for shots over 1 second to reduce hot pixels and fixed pattern noise — the camera takes a dark frame automatically and subtracts it.",
  "Set APERTURE RING SETTING (A) to COMMAND DIAL so when the aperture ring is on A, you can control aperture with the front command dial instead of the ring.",
  "Enable LOCATION INFO and pair with the FUJIFILM XApp on your smartphone via Bluetooth to geotag your photos automatically without a dedicated GPS unit.",
  "Use DISP CUSTOM SETTING to create a clean shooting display with no overlays — just the image — for times when you want a distraction-free framing experience.",
  "Try shooting with WHITE BALANCE set to KELVIN manually — around 4000K for a cool blue tone in shade, or 7500K for a warm golden look in cloudy conditions.",
  "Use the PHOTOBOOK ASSIST feature in the Playback Menu to pre-select and organize up to 300 images for a photo book order directly from the camera.",
  "Enable IS MODE BOOST for movie recording in very low light or when handheld shooting at long distances — it increases stabilization power at the cost of a slight crop.",
  "Use TALLY LIGHT setting to make the AF-assist lamp blink during movie recording — a useful signal to talent or crew that the camera is rolling.",
  "Set INTERVAL PRIORITY MODE to ON for timelapses to ensure consistent frame intervals — the camera will adjust exposure slightly to hit the interval rather than skip frames.",
  "Use the CONTROL RING to adjust the digital teleconverter in Standard mode — rotate to switch between 1x, 1.4x (35mm eq.), and 2x (50mm eq.) crops on the fly.",
  "Assign FLASH FUNCTION SETTING to a Function button for quick flash mode changes between TTL, manual, and commander mode when shooting with external flash.",
  "Use RED EYE REMOVAL set to ON when shooting flash portraits in JPEG mode — the camera automatically detects and corrects red-eye during in-camera processing.",
  "Set NATURAL LIVE VIEW to ON if you find the EVF preview too contrasty or color-heavy — it shows a more neutral, film-like rendering of the live image in the finder.",
  "Use CROP in the Playback Menu to trim and save a new JPEG version of any image directly in-camera — useful for quick social media crops without needing a computer.",
  "Set SAVE SELF-TIMER SETTING to ON so your self-timer delay preference is remembered even after the camera is turned off — no need to reset it every time.",
  "Use VOICE MEMO SETTING to record a short audio note attached to any image in playback — helpful for remembering location info, client notes, or story context.",
  "Enable F-Log/HLG RECORDING for video when you're planning to color grade in post — F-Log gives the widest dynamic range, while HLG is great for HDR-ready delivery.",
  "Use ZEBRA SETTING in movie mode and set ZEBRA LEVEL to 95–100 to highlight overexposed areas in real time — essential for protecting highlights when shooting video.",
  "Set WIND FILTER to ON for outdoor video recording to reduce low-frequency wind rumble on the internal mic without needing an external windshield accessory.",
  "Use LOW CUT FILTER in audio settings for movie recording to cut bass frequencies below ~80Hz — helps eliminate AC hum, traffic rumble, and handling noise.",
  "Try the TTL-LOCK MODE for flash so you can meter the flash output once and lock it, then freely recompose or change subjects without the flash recalculating each time.",
  "Use PROTECT in the Playback Menu to lock your best frames so they can't be accidentally deleted — great habit after a shoot before you start culling.",
  "Set SELECT JPEG/HEIF to HEIF for smaller file sizes with better quality than JPEG at the same bit depth — compatible with modern Apple devices and increasingly with other apps.",
  "Use the RAW CONVERSION feature in the Playback Menu to apply different film simulations to your RAW files directly in-camera and save new JPEGs without a computer.",
  "Assign the Q button shortcut to put WHITE BALANCE SHIFT in your Quick Menu — lets you quickly warm or cool white balance by fine-tuning in the amber/blue axis.",
  "Use TOUCH SCREEN SETTING > TOUCH FUNCTION to assign swipe gestures on the LCD to specific controls like film simulation, ISO, or WB during shooting.",
  "Set COMMAND DIAL SETTING to control different parameters — for example, have the front dial control ISO in M mode and the rear dial control shutter speed independently.",
  "Use the ERF (Electronic Rangefinder) window in the OVF to confirm focus when shooting in Single Point AF — it shows a magnified focus preview while keeping the optical view.",
  "Enable FLICKERLESS S.S. SETTING to automatically detect your local power frequency and set a shutter speed that minimizes flicker — critical under fluorescent lights.",
  "Use PRINT ORDER (DPOF) in the Playback Menu to mark photos for printing at a photo lab directly from your memory card without needing a computer.",
  "Set EVF BRIGHTNESS and LCD BRIGHTNESS independently — boost EVF brightness in bright outdoor conditions and reduce LCD brightness at night to preserve your vision.",
  "Use GEOTAGGING in SAVE DATA SETTING to embed GPS coordinates in your images via the smartphone app connection — perfect for travel photography organization.",
  "Assign FOCUS CHECK to a Function button so pressing it instantly magnifies the active focus area in the EVF or LCD, letting you confirm sharpness without going to playback.",
  "Use the FRAME NO. setting in SAVE DATA SETTING to set file numbering to CONTINUOUS so frame numbers never reset between card formats, keeping your library uniquely numbered.",
  "Set COPYRIGHT INFO in SAVE DATA SETTING to embed your name and copyright notice into every image's EXIF data automatically — saves time in post-processing.",
  "Use EDIT FILE NAME to set a custom 4-character prefix for your files — use something like your initials so images are instantly identifiable in a shared folder.",
  "Enable AUTO POWER OFF TEMP set to HIGH if you're shooting extended video sessions in warm conditions — it reduces the chance of the camera shutting down due to heat.",
  "Use SENSOR CLEANING in USER SETTING to run the automatic sensor vibration cleaning cycle after swapping accessories or working in dusty conditions.",
  "Check SHUTTER COUNT in USER SETTING to see how many actuations your camera has accumulated — useful for tracking wear, especially if buying or selling a used body."
];
